version: '3'

services:
  app:
    command: npm run dev
    volumes: 
      - ./app:/usr/src/app
    stdin_open: true
    tty: true
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf